// <auto-generated />
using System;
using IoTCircuitBuilder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTCircuitBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlashMemoryKb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is5VTolerant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LogicLevelV")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCurrentMa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessorSpeedHz")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SramKb")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("BoardId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Arduino Uno R3",
                            FlashMemoryKb = 32,
                            Is5VTolerant = true,
                            IsActive = true,
                            LogicLevelV = 5.0m,
                            Manufacturer = "Arduino",
                            MaxCurrentMa = 500,
                            Name = "arduino_uno",
                            ProcessorSpeedHz = 16000000,
                            SramKb = 2,
                            Voltage = 5.0m
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.CodeTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateId");

                    b.HasIndex("ComponentId");

                    b.ToTable("CodeTemplates");

                    b.HasData(
                        new
                        {
                            TemplateId = 1,
                            ComponentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_out }}, INPUT);  // {{ display_name }}",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 2,
                            ComponentId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "int ir_{{ instance_id }} = digitalRead({{ pin_out }});\r\nSerial.print(\"IR Sensor {{ instance_id }}: \");\r\nSerial.println(ir_{{ instance_id }} == LOW ? \"DETECTED\" : \"clear\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 3,
                            ComponentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "NewPing sonar_{{ instance_id }}({{ pin_trig }}, {{ pin_echo }}, 200);",
                            TemplateType = "declaration"
                        },
                        new
                        {
                            TemplateId = 4,
                            ComponentId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "unsigned int distance_{{ instance_id }} = sonar_{{ instance_id }}.ping_cm();\r\nSerial.print(\"Distance {{ instance_id }}: \");\r\nSerial.print(distance_{{ instance_id }});\r\nSerial.println(\" cm\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 5,
                            ComponentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_ena }}, OUTPUT);  // Motor A speed (PWM)\r\npinMode({{ pin_in1 }}, OUTPUT);  // Motor A direction\r\npinMode({{ pin_in2 }}, OUTPUT);\r\npinMode({{ pin_enb }}, OUTPUT);  // Motor B speed (PWM)\r\npinMode({{ pin_in3 }}, OUTPUT);  // Motor B direction\r\npinMode({{ pin_in4 }}, OUTPUT);",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 23,
                            ComponentId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "// Drive both motors FORWARD at 75% speed\r\ndigitalWrite({{ pin_in1 }}, HIGH);\r\ndigitalWrite({{ pin_in2 }}, LOW);\r\nanalogWrite({{ pin_ena }}, 190);  // 0-255 speed\r\n\r\ndigitalWrite({{ pin_in3 }}, HIGH);\r\ndigitalWrite({{ pin_in4 }}, LOW);\r\nanalogWrite({{ pin_enb }}, 190);\r\n\r\nSerial.println(\"Motors: FORWARD at 75%\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 6,
                            ComponentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "Servo servo_{{ instance_id }};",
                            TemplateType = "declaration"
                        },
                        new
                        {
                            TemplateId = 7,
                            ComponentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "servo_{{ instance_id }}.attach({{ pin_signal }});\r\nservo_{{ instance_id }}.write(90);  // Center position",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 24,
                            ComponentId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "// Sweep servo {{ instance_id }}: 0° → 180° → 0°\r\nfor (int angle = 0; angle <= 180; angle += 5) {\r\n  servo_{{ instance_id }}.write(angle);\r\n  delay(15);\r\n}\r\nfor (int angle = 180; angle >= 0; angle -= 5) {\r\n  servo_{{ instance_id }}.write(angle);\r\n  delay(15);\r\n}",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 8,
                            ComponentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_anode }}, OUTPUT);  // {{ display_name }}",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 25,
                            ComponentId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "digitalWrite({{ pin_anode }}, HIGH);  // LED {{ instance_id }} ON\r\ndelay(500);\r\ndigitalWrite({{ pin_anode }}, LOW);   // LED {{ instance_id }} OFF\r\ndelay(500);",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 9,
                            ComponentId = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "int pot_{{ instance_id }} = analogRead({{ pin_signal }});  // 0-1023\r\nint mapped_{{ instance_id }} = map(pot_{{ instance_id }}, 0, 1023, 0, 180);  // Map to 0-180\r\nSerial.print(\"Pot {{ instance_id }}: \");\r\nSerial.print(pot_{{ instance_id }});\r\nSerial.print(\" → mapped: \");\r\nSerial.println(mapped_{{ instance_id }});",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 10,
                            ComponentId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "Adafruit_BME280 bme_{{ instance_id }};",
                            TemplateType = "declaration"
                        },
                        new
                        {
                            TemplateId = 11,
                            ComponentId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "Wire.begin();\r\nif (!bme_{{ instance_id }}.begin(0x76)) {\r\n  Serial.println(\"BME280 not found! Check wiring.\");\r\n  while (1) delay(10);  // Halt if sensor missing\r\n}",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 12,
                            ComponentId = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "float temp_{{ instance_id }} = bme_{{ instance_id }}.readTemperature();\r\nfloat hum_{{ instance_id }} = bme_{{ instance_id }}.readHumidity();\r\nfloat pres_{{ instance_id }} = bme_{{ instance_id }}.readPressure() / 100.0F;\r\nSerial.print(\"Temp: \"); Serial.print(temp_{{ instance_id }}); Serial.print(\"°C  \");\r\nSerial.print(\"Humidity: \"); Serial.print(hum_{{ instance_id }}); Serial.print(\"%  \");\r\nSerial.print(\"Pressure: \"); Serial.print(pres_{{ instance_id }}); Serial.println(\" hPa\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 13,
                            ComponentId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "#define SCREEN_WIDTH 128\n#define SCREEN_HEIGHT 64\nAdafruit_SSD1306 display_{{ instance_id }}(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);",
                            TemplateType = "declaration"
                        },
                        new
                        {
                            TemplateId = 14,
                            ComponentId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "if (!display_{{ instance_id }}.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {\r\n  Serial.println(\"OLED not found! Check wiring.\");\r\n  while (1) delay(10);  // Halt if display missing\r\n}\r\ndisplay_{{ instance_id }}.clearDisplay();\r\ndisplay_{{ instance_id }}.setTextSize(1);\r\ndisplay_{{ instance_id }}.setTextColor(SSD1306_WHITE);",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 26,
                            ComponentId = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "display_{{ instance_id }}.clearDisplay();\r\ndisplay_{{ instance_id }}.setCursor(0, 0);\r\ndisplay_{{ instance_id }}.println(\"IoT Circuit Builder\");\r\ndisplay_{{ instance_id }}.println(\"──────────────────\");\r\ndisplay_{{ instance_id }}.print(\"Uptime: \");\r\ndisplay_{{ instance_id }}.print(millis() / 1000);\r\ndisplay_{{ instance_id }}.println(\"s\");\r\ndisplay_{{ instance_id }}.display();",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 15,
                            ComponentId = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "int light_{{ instance_id }} = analogRead({{ pin_signal }});  // 0=dark, 1023=bright\r\nSerial.print(\"Light {{ instance_id }}: \");\r\nSerial.print(light_{{ instance_id }});\r\nSerial.println(light_{{ instance_id }} < 300 ? \" (DARK)\" : \" (BRIGHT)\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 16,
                            ComponentId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "DHT dht_{{ instance_id }}({{ pin_data }}, DHT11);",
                            TemplateType = "declaration"
                        },
                        new
                        {
                            TemplateId = 17,
                            ComponentId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "dht_{{ instance_id }}.begin();",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 18,
                            ComponentId = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "float temp_{{ instance_id }} = dht_{{ instance_id }}.readTemperature();\r\nfloat hum_{{ instance_id }} = dht_{{ instance_id }}.readHumidity();\r\nif (isnan(temp_{{ instance_id }}) || isnan(hum_{{ instance_id }})) {\r\n  Serial.println(\"DHT {{ instance_id }}: Read failed!\");\r\n} else {\r\n  Serial.print(\"DHT {{ instance_id }}: \");\r\n  Serial.print(temp_{{ instance_id }}); Serial.print(\"°C  \");\r\n  Serial.print(hum_{{ instance_id }}); Serial.println(\"%\");\r\n}",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 19,
                            ComponentId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_signal }}, OUTPUT);  // {{ display_name }}",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 27,
                            ComponentId = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "tone({{ pin_signal }}, 1000, 200);  // 1kHz beep for 200ms\r\ndelay(300);\r\ntone({{ pin_signal }}, 1500, 200);  // 1.5kHz beep\r\ndelay(300);\r\nnoTone({{ pin_signal }});\r\nSerial.println(\"Buzzer: beep pattern\");",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 20,
                            ComponentId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_signal }}, INPUT_PULLUP);  // {{ display_name }} (LOW = pressed)",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 21,
                            ComponentId = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "bool btn_{{ instance_id }} = !digitalRead({{ pin_signal }});  // LOW = pressed\r\nif (btn_{{ instance_id }}) {\r\n  Serial.println(\"Button {{ instance_id }}: PRESSED\");\r\n}",
                            TemplateType = "loop"
                        },
                        new
                        {
                            TemplateId = 22,
                            ComponentId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "pinMode({{ pin_signal }}, OUTPUT);\r\ndigitalWrite({{ pin_signal }}, HIGH);  // Relay OFF (active LOW)",
                            TemplateType = "setup"
                        },
                        new
                        {
                            TemplateId = 28,
                            ComponentId = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Language = "cpp",
                            TemplateContent = "digitalWrite({{ pin_signal }}, LOW);   // Relay ON\r\nSerial.println(\"Relay {{ instance_id }}: ON\");\r\ndelay(2000);\r\ndigitalWrite({{ pin_signal }}, HIGH);  // Relay OFF\r\nSerial.println(\"Relay {{ instance_id }}: OFF\");\r\ndelay(2000);",
                            TemplateType = "loop"
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentDrawMa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterfaceProtocol")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresExternalPower")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresLevelShifter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VoltageMax")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VoltageMin")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ComponentId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            ComponentId = 1,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 20,
                            DisplayName = "TCRT5000 IR Proximity Sensor",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "ir_sensor",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 2,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 15,
                            DisplayName = "HC-SR04 Ultrasonic Distance Sensor",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "hc_sr04_ultrasonic",
                            VoltageMax = 5.0m,
                            VoltageMin = 5.0m
                        },
                        new
                        {
                            ComponentId = 3,
                            Category = "motor_driver",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 50,
                            DisplayName = "L298N Dual H-Bridge Motor Driver",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = true,
                            RequiresLevelShifter = false,
                            Type = "l298n_motor_driver",
                            VoltageMax = 46.0m,
                            VoltageMin = 5.0m
                        },
                        new
                        {
                            ComponentId = 4,
                            Category = "actuator",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 200,
                            DisplayName = "Generic DC Motor",
                            InterfaceProtocol = "driver",
                            IsActive = true,
                            RequiresExternalPower = true,
                            RequiresLevelShifter = false,
                            Type = "dc_motor",
                            VoltageMax = 12.0m,
                            VoltageMin = 3.0m
                        },
                        new
                        {
                            ComponentId = 5,
                            Category = "actuator",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 100,
                            DisplayName = "SG90 Micro Servo",
                            InterfaceProtocol = "pwm",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "sg90_servo",
                            VoltageMax = 6.0m,
                            VoltageMin = 4.8m
                        },
                        new
                        {
                            ComponentId = 6,
                            Category = "indicator",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 20,
                            DisplayName = "Red LED 5mm",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "led_red",
                            VoltageMax = 5.0m,
                            VoltageMin = 2.0m
                        },
                        new
                        {
                            ComponentId = 7,
                            Category = "input",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 1,
                            DisplayName = "10K Potentiometer",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "potentiometer",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 8,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 1,
                            DisplayName = "BME280 Temperature/Humidity/Pressure Sensor",
                            InterfaceProtocol = "i2c",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "bme280",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 9,
                            Category = "display",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 20,
                            DisplayName = "SSD1306 OLED Display 0.96\" 128x64",
                            InterfaceProtocol = "i2c",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "oled_128x64",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 10,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 1,
                            DisplayName = "LDR Light Sensor (Photoresistor)",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "ldr_sensor",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 11,
                            Category = "sensor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 2,
                            DisplayName = "DHT11 Temperature & Humidity Sensor",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "dht11",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 12,
                            Category = "actuator",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 30,
                            DisplayName = "Piezo Buzzer",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "buzzer",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 13,
                            Category = "input",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "Momentary Push Button",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "push_button",
                            VoltageMax = 5.0m,
                            VoltageMin = 3.3m
                        },
                        new
                        {
                            ComponentId = 14,
                            Category = "actuator",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 75,
                            DisplayName = "5V Relay Module",
                            InterfaceProtocol = "digital",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "relay_module",
                            VoltageMax = 5.0m,
                            VoltageMin = 5.0m
                        },
                        new
                        {
                            ComponentId = 15,
                            Category = "power",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "9V Battery",
                            InterfaceProtocol = "power",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "battery_9v",
                            VoltageMax = 9.0m,
                            VoltageMin = 9.0m
                        },
                        new
                        {
                            ComponentId = 16,
                            Category = "passive",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "Resistor (Inline)",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "resistor",
                            VoltageMax = 100m,
                            VoltageMin = 0m
                        },
                        new
                        {
                            ComponentId = 17,
                            Category = "passive",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "Diode (1N4001)",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "diode",
                            VoltageMax = 100m,
                            VoltageMin = 0m
                        },
                        new
                        {
                            ComponentId = 18,
                            Category = "passive",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "Ceramic Capacitor (100nF)",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "capacitor_ceramic",
                            VoltageMax = 50m,
                            VoltageMin = 0m
                        },
                        new
                        {
                            ComponentId = 19,
                            Category = "passive",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentDrawMa = 0,
                            DisplayName = "Electrolytic Capacitor (10uF)",
                            InterfaceProtocol = "analog",
                            IsActive = true,
                            RequiresExternalPower = false,
                            RequiresLevelShifter = false,
                            Type = "capacitor_electrolytic",
                            VoltageMax = 50m,
                            VoltageMin = 0m
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.ComponentLibrary", b =>
                {
                    b.Property<int>("ComponentLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComponentLibraryId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ComponentId", "LibraryId")
                        .IsUnique();

                    b.ToTable("ComponentLibraries");

                    b.HasData(
                        new
                        {
                            ComponentLibraryId = 1,
                            ComponentId = 2,
                            IsRequired = true,
                            LibraryId = 1
                        },
                        new
                        {
                            ComponentLibraryId = 2,
                            ComponentId = 5,
                            IsRequired = true,
                            LibraryId = 2
                        },
                        new
                        {
                            ComponentLibraryId = 3,
                            ComponentId = 8,
                            IsRequired = true,
                            LibraryId = 3
                        },
                        new
                        {
                            ComponentLibraryId = 4,
                            ComponentId = 8,
                            IsRequired = true,
                            LibraryId = 4
                        },
                        new
                        {
                            ComponentLibraryId = 5,
                            ComponentId = 9,
                            IsRequired = true,
                            LibraryId = 3
                        },
                        new
                        {
                            ComponentLibraryId = 6,
                            ComponentId = 9,
                            IsRequired = true,
                            LibraryId = 5
                        },
                        new
                        {
                            ComponentLibraryId = 7,
                            ComponentId = 11,
                            IsRequired = true,
                            LibraryId = 6
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.ComponentPinRequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErcType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequirementId");

                    b.HasIndex("ComponentId", "PinName")
                        .IsUnique();

                    b.ToTable("ComponentPinRequirements");

                    b.HasData(
                        new
                        {
                            RequirementId = 1,
                            ComponentId = 1,
                            ErcType = 2,
                            IsOptional = false,
                            PinName = "OUT",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 2,
                            ComponentId = 1,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 3,
                            ComponentId = 1,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 4,
                            ComponentId = 2,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "TRIG",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 5,
                            ComponentId = 2,
                            ErcType = 2,
                            IsOptional = false,
                            PinName = "ECHO",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 6,
                            ComponentId = 2,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 7,
                            ComponentId = 2,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 8,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "ENA",
                            RequiredCapability = "Pwm"
                        },
                        new
                        {
                            RequirementId = 9,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "IN1",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 10,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "IN2",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 11,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "ENB",
                            RequiredCapability = "Pwm"
                        },
                        new
                        {
                            RequirementId = 12,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "IN3",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 13,
                            ComponentId = 3,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "IN4",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 14,
                            ComponentId = 5,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Pwm"
                        },
                        new
                        {
                            RequirementId = 15,
                            ComponentId = 5,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 16,
                            ComponentId = 5,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 17,
                            ComponentId = 6,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "ANODE",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 18,
                            ComponentId = 6,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "CATHODE",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 19,
                            ComponentId = 7,
                            ErcType = 2,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 20,
                            ComponentId = 7,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 21,
                            ComponentId = 7,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 22,
                            ComponentId = 8,
                            ErcType = 3,
                            IsOptional = false,
                            PinName = "SDA",
                            RequiredCapability = "I2cSda"
                        },
                        new
                        {
                            RequirementId = 23,
                            ComponentId = 8,
                            ErcType = 3,
                            IsOptional = false,
                            PinName = "SCL",
                            RequiredCapability = "I2cScl"
                        },
                        new
                        {
                            RequirementId = 24,
                            ComponentId = 8,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 25,
                            ComponentId = 8,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 26,
                            ComponentId = 9,
                            ErcType = 3,
                            IsOptional = false,
                            PinName = "SDA",
                            RequiredCapability = "I2cSda"
                        },
                        new
                        {
                            RequirementId = 27,
                            ComponentId = 9,
                            ErcType = 3,
                            IsOptional = false,
                            PinName = "SCL",
                            RequiredCapability = "I2cScl"
                        },
                        new
                        {
                            RequirementId = 28,
                            ComponentId = 9,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 29,
                            ComponentId = 9,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 30,
                            ComponentId = 10,
                            ErcType = 2,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 31,
                            ComponentId = 10,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 32,
                            ComponentId = 10,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 33,
                            ComponentId = 11,
                            ErcType = 3,
                            IsOptional = false,
                            PinName = "DATA",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 34,
                            ComponentId = 11,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 35,
                            ComponentId = 11,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 36,
                            ComponentId = 12,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 37,
                            ComponentId = 12,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 38,
                            ComponentId = 13,
                            ErcType = 2,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 39,
                            ComponentId = 13,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 40,
                            ComponentId = 14,
                            ErcType = 1,
                            IsOptional = false,
                            PinName = "SIGNAL",
                            RequiredCapability = "Digital"
                        },
                        new
                        {
                            RequirementId = 41,
                            ComponentId = 14,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 42,
                            ComponentId = 14,
                            ErcType = 4,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 43,
                            ComponentId = 15,
                            ErcType = 5,
                            IsOptional = false,
                            PinName = "VCC",
                            RequiredCapability = "Power5V"
                        },
                        new
                        {
                            RequirementId = 44,
                            ComponentId = 15,
                            ErcType = 5,
                            IsOptional = false,
                            PinName = "GND",
                            RequiredCapability = "Ground"
                        },
                        new
                        {
                            RequirementId = 45,
                            ComponentId = 16,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "PIN1",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 46,
                            ComponentId = 16,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "PIN2",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 47,
                            ComponentId = 17,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "ANODE",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 48,
                            ComponentId = 17,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "CATHODE",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 49,
                            ComponentId = 18,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "PIN1",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 50,
                            ComponentId = 18,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "PIN2",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 51,
                            ComponentId = 19,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "ANODE",
                            RequiredCapability = "Analog"
                        },
                        new
                        {
                            RequirementId = 52,
                            ComponentId = 19,
                            ErcType = 6,
                            IsOptional = false,
                            PinName = "CATHODE",
                            RequiredCapability = "Ground"
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.I2cAddress", b =>
                {
                    b.Property<int>("I2cAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateAddresses")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfigurable")
                        .HasColumnType("INTEGER");

                    b.HasKey("I2cAddressId");

                    b.HasIndex("ComponentId");

                    b.ToTable("I2cAddresses");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Library", b =>
                {
                    b.Property<int>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallCommand")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            LibraryId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://github.com/microflo/NewPing",
                            InstallCommand = "#include <NewPing.h>",
                            IsDeprecated = false,
                            Name = "NewPing",
                            Version = "1.9.7"
                        },
                        new
                        {
                            LibraryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://github.com/arduino-libraries/Servo",
                            InstallCommand = "#include <Servo.h>",
                            IsDeprecated = false,
                            Name = "Servo",
                            Version = "1.2.1"
                        },
                        new
                        {
                            LibraryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://www.arduino.cc/reference/en/language/functions/communication/wire/",
                            InstallCommand = "#include <Wire.h>",
                            IsDeprecated = false,
                            Name = "Wire",
                            Version = "builtin"
                        },
                        new
                        {
                            LibraryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://github.com/adafruit/Adafruit_BME280_Library",
                            InstallCommand = "#include <Adafruit_BME280.h>",
                            IsDeprecated = false,
                            Name = "Adafruit_BME280",
                            Version = "2.2.4"
                        },
                        new
                        {
                            LibraryId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://github.com/adafruit/Adafruit_SSD1306",
                            InstallCommand = "#include <Adafruit_SSD1306.h>",
                            IsDeprecated = false,
                            Name = "Adafruit_SSD1306",
                            Version = "2.5.9"
                        },
                        new
                        {
                            LibraryId = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GithubUrl = "https://github.com/adafruit/DHT-sensor-library",
                            InstallCommand = "#include <DHT.h>",
                            IsDeprecated = false,
                            Name = "DHT",
                            Version = "1.4.6"
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Pin", b =>
                {
                    b.Property<int>("PinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseErcType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCurrentMa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicalPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("PinId");

                    b.HasIndex("BoardId", "PinIdentifier")
                        .IsUnique();

                    b.ToTable("Pins");

                    b.HasData(
                        new
                        {
                            PinId = 1,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 0,
                            PinIdentifier = "D0",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 2,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 1,
                            PinIdentifier = "D1",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 3,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 2,
                            PinIdentifier = "D2",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 4,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 3,
                            PinIdentifier = "D3",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 5,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 4,
                            PinIdentifier = "D4",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 6,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 5,
                            PinIdentifier = "D5",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 7,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 6,
                            PinIdentifier = "D6",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 8,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 7,
                            PinIdentifier = "D7",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 9,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 8,
                            PinIdentifier = "D8",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 10,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 9,
                            PinIdentifier = "D9",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 11,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 10,
                            PinIdentifier = "D10",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 12,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 11,
                            PinIdentifier = "D11",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 13,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 12,
                            PinIdentifier = "D12",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 14,
                            BaseErcType = 3,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 13,
                            PinIdentifier = "D13",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 15,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 14,
                            PinIdentifier = "A0",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 16,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 15,
                            PinIdentifier = "A1",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 17,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 16,
                            PinIdentifier = "A2",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 18,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 17,
                            PinIdentifier = "A3",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 19,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 18,
                            PinIdentifier = "A4",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 20,
                            BaseErcType = 1,
                            BoardId = 1,
                            MaxCurrentMa = 40,
                            PhysicalPosition = 19,
                            PinIdentifier = "A5",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 21,
                            BaseErcType = 5,
                            BoardId = 1,
                            MaxCurrentMa = 500,
                            PhysicalPosition = 100,
                            PinIdentifier = "5V",
                            Voltage = 5.0m
                        },
                        new
                        {
                            PinId = 22,
                            BaseErcType = 5,
                            BoardId = 1,
                            MaxCurrentMa = 50,
                            PhysicalPosition = 101,
                            PinIdentifier = "3V3",
                            Voltage = 3.3m
                        },
                        new
                        {
                            PinId = 23,
                            BaseErcType = 5,
                            BoardId = 1,
                            MaxCurrentMa = 1000,
                            PhysicalPosition = 102,
                            PinIdentifier = "GND",
                            Voltage = 0m
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.PinCapability", b =>
                {
                    b.Property<int>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CapabilityId");

                    b.HasIndex("PinId", "CapabilityType")
                        .IsUnique();

                    b.ToTable("PinCapabilities");

                    b.HasData(
                        new
                        {
                            CapabilityId = 1,
                            CapabilityType = "Digital",
                            PinId = 1
                        },
                        new
                        {
                            CapabilityId = 2,
                            CapabilityType = "Digital",
                            PinId = 2
                        },
                        new
                        {
                            CapabilityId = 3,
                            CapabilityType = "Digital",
                            PinId = 3
                        },
                        new
                        {
                            CapabilityId = 4,
                            CapabilityType = "Digital",
                            PinId = 4
                        },
                        new
                        {
                            CapabilityId = 5,
                            CapabilityType = "Digital",
                            PinId = 5
                        },
                        new
                        {
                            CapabilityId = 6,
                            CapabilityType = "Digital",
                            PinId = 6
                        },
                        new
                        {
                            CapabilityId = 7,
                            CapabilityType = "Digital",
                            PinId = 7
                        },
                        new
                        {
                            CapabilityId = 8,
                            CapabilityType = "Digital",
                            PinId = 8
                        },
                        new
                        {
                            CapabilityId = 9,
                            CapabilityType = "Digital",
                            PinId = 9
                        },
                        new
                        {
                            CapabilityId = 10,
                            CapabilityType = "Digital",
                            PinId = 10
                        },
                        new
                        {
                            CapabilityId = 11,
                            CapabilityType = "Digital",
                            PinId = 11
                        },
                        new
                        {
                            CapabilityId = 12,
                            CapabilityType = "Digital",
                            PinId = 12
                        },
                        new
                        {
                            CapabilityId = 13,
                            CapabilityType = "Digital",
                            PinId = 13
                        },
                        new
                        {
                            CapabilityId = 14,
                            CapabilityType = "Digital",
                            PinId = 14
                        },
                        new
                        {
                            CapabilityId = 15,
                            CapabilityType = "Pwm",
                            PinId = 4
                        },
                        new
                        {
                            CapabilityId = 16,
                            CapabilityType = "Pwm",
                            PinId = 6
                        },
                        new
                        {
                            CapabilityId = 17,
                            CapabilityType = "Pwm",
                            PinId = 7
                        },
                        new
                        {
                            CapabilityId = 18,
                            CapabilityType = "Pwm",
                            PinId = 10
                        },
                        new
                        {
                            CapabilityId = 19,
                            CapabilityType = "Pwm",
                            PinId = 11
                        },
                        new
                        {
                            CapabilityId = 20,
                            CapabilityType = "Pwm",
                            PinId = 12
                        },
                        new
                        {
                            CapabilityId = 21,
                            CapabilityType = "Analog",
                            PinId = 15
                        },
                        new
                        {
                            CapabilityId = 22,
                            CapabilityType = "Digital",
                            PinId = 15
                        },
                        new
                        {
                            CapabilityId = 23,
                            CapabilityType = "Analog",
                            PinId = 16
                        },
                        new
                        {
                            CapabilityId = 24,
                            CapabilityType = "Digital",
                            PinId = 16
                        },
                        new
                        {
                            CapabilityId = 25,
                            CapabilityType = "Analog",
                            PinId = 17
                        },
                        new
                        {
                            CapabilityId = 26,
                            CapabilityType = "Digital",
                            PinId = 17
                        },
                        new
                        {
                            CapabilityId = 27,
                            CapabilityType = "Analog",
                            PinId = 18
                        },
                        new
                        {
                            CapabilityId = 28,
                            CapabilityType = "Digital",
                            PinId = 18
                        },
                        new
                        {
                            CapabilityId = 29,
                            CapabilityType = "Analog",
                            PinId = 19
                        },
                        new
                        {
                            CapabilityId = 30,
                            CapabilityType = "Digital",
                            PinId = 19
                        },
                        new
                        {
                            CapabilityId = 31,
                            CapabilityType = "Analog",
                            PinId = 20
                        },
                        new
                        {
                            CapabilityId = 32,
                            CapabilityType = "Digital",
                            PinId = 20
                        },
                        new
                        {
                            CapabilityId = 33,
                            CapabilityType = "I2cSda",
                            PinId = 19
                        },
                        new
                        {
                            CapabilityId = 34,
                            CapabilityType = "I2cScl",
                            PinId = 20
                        },
                        new
                        {
                            CapabilityId = 35,
                            CapabilityType = "SpiMosi",
                            PinId = 12
                        },
                        new
                        {
                            CapabilityId = 36,
                            CapabilityType = "SpiMiso",
                            PinId = 13
                        },
                        new
                        {
                            CapabilityId = 37,
                            CapabilityType = "SpiSck",
                            PinId = 14
                        },
                        new
                        {
                            CapabilityId = 38,
                            CapabilityType = "UartRx",
                            PinId = 1
                        },
                        new
                        {
                            CapabilityId = 39,
                            CapabilityType = "UartTx",
                            PinId = 2
                        },
                        new
                        {
                            CapabilityId = 40,
                            CapabilityType = "Power5V",
                            PinId = 21
                        },
                        new
                        {
                            CapabilityId = 41,
                            CapabilityType = "Power3V3",
                            PinId = 22
                        },
                        new
                        {
                            CapabilityId = 42,
                            CapabilityType = "Ground",
                            PinId = 23
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.PowerDistributionRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCurrentMa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PowerSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VoltageV")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("RuleId");

                    b.HasIndex("BoardId");

                    b.ToTable("PowerDistributionRules");

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            BoardId = 1,
                            Description = "USB 2.0 power supply",
                            MaxCurrentMa = 500,
                            PowerSource = "usb",
                            VoltageV = 5.0m
                        },
                        new
                        {
                            RuleId = 2,
                            BoardId = 1,
                            Description = "Barrel jack via onboard regulator",
                            MaxCurrentMa = 1000,
                            PowerSource = "barrel",
                            VoltageV = 5.0m
                        },
                        new
                        {
                            RuleId = 3,
                            BoardId = 1,
                            Description = "3.3V rail from onboard LDO",
                            MaxCurrentMa = 50,
                            PowerSource = "3v3_pin",
                            VoltageV = 3.3m
                        });
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.CodeTemplate", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Component", "Component")
                        .WithMany("CodeTemplates")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.ComponentLibrary", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Component", "Component")
                        .WithMany("ComponentLibraries")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Library", "Library")
                        .WithMany("ComponentLibraries")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.ComponentPinRequirement", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Component", "Component")
                        .WithMany("PinRequirements")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.I2cAddress", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Component", "Component")
                        .WithMany("I2cAddresses")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Pin", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Board", "Board")
                        .WithMany("Pins")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.PinCapability", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Pin", "Pin")
                        .WithMany("Capabilities")
                        .HasForeignKey("PinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pin");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.PowerDistributionRule", b =>
                {
                    b.HasOne("IoTCircuitBuilder.Domain.Entities.Board", "Board")
                        .WithMany("PowerDistributionRules")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Board", b =>
                {
                    b.Navigation("Pins");

                    b.Navigation("PowerDistributionRules");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Component", b =>
                {
                    b.Navigation("CodeTemplates");

                    b.Navigation("ComponentLibraries");

                    b.Navigation("I2cAddresses");

                    b.Navigation("PinRequirements");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Library", b =>
                {
                    b.Navigation("ComponentLibraries");
                });

            modelBuilder.Entity("IoTCircuitBuilder.Domain.Entities.Pin", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
